In [8]:
import pandas as pd
df=pd.read_csv("C:\\Users\\osm\\Downloads\\weather.csv")

In [10]:
df

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [11]:
df.head(5)

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon

In [12]:
df.tail(5)

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [17]:



df.shape[0] 
df.shape[1]

11

In [18]:
df.shape[0]

31

In [19]:
df.shape[1]

11

In [21]:
import pandas as pd

# Example: Load dataset
df = pd.read_csv("C:\\Users\\osm\\Downloads\\weather.csv")

# Check shape
print(df.shape)  # Output: (rows, columns)


df.shape[0] 
df.shape[1]

(31, 11)

11

In [22]:
print(df.columns[:5])

Index(['MIN temp (deg Celcius)', 'Location', 'Time', 'Wind',
       'MAX temp (deg Celcius)'],
      dtype='object')

In [23]:
print(df.dtypes)

MIN temp (deg Celcius)    object
Location                  object
Time                      object
Wind                      object
MAX temp (deg Celcius)    object
Description               object
Precipitation (in %)      object
Date                      object
Other Details             object
Humidity (in %)           object
Day                       object
dtype: object

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MIN temp (deg Celcius)  31 non-null     object
 1   Location                31 non-null     object
 2   Time                    31 non-null     object
 3   Wind                    31 non-null     object
 4   MAX temp (deg Celcius)  31 non-null     object
 5   Description             31 non-null     object
 6   Precipitation (in %)    31 non-null     object
 7   Date                    31 non-null     object
 8   Other Details           31 non-null     object
 9   Humidity (in %)         31 non-null     object
 10  Day                     31 non-null     object
dtypes: object(11)
memory usage: 2.8+ KB

In [25]:
summary = df.describe()
print(summary)

       MIN temp (deg Celcius)                       Location       Time  \
count                      31                             31         31
unique                      5                              2          2
top                        19  Bharsul, India 10-day Weather  23:04 IST
freq                       12                             30         30

              Wind MAX temp (deg Celcius) Description Precipitation (in %)  \
count           31                     31          31                   31
unique          16                      6           4                    2
top     NE 2 km/h                      33       Sunny                    0
freq             2                     10          20                   30

          Date                                      Other Details  \
count       31                                                 31
unique      16                                                 16
top     18 OCT  Generally clear. Low 22ºC. Winds NE and variable.
freq         2                                                  2

       Humidity (in %)  Day
count               31   31
unique               9    9
top                 29  Fri
freq                 8    4

In [42]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Pulse': [72, 88, 95, 67]
}

df = pd.DataFrame(data)

# Find the maximum pulse value
max_pulse = df['Pulse'].max()

# Find the row(s) corresponding to the maximum pulse value
max_pulse_rows = df[df['Pulse'] == max_pulse]

# Output results
print(f"Maximum pulse value: {max_pulse}")
print("Row(s) with maximum pulse value:")
print(max_pulse_rows)

Maximum pulse value: 95
Row(s) with maximum pulse value:
      Name  Pulse
2  Charlie     95

In [48]:
df.min()

Name     Alice
Pulse       67
dtype: object

In [49]:
df.max()

Name     David
Pulse       95
dtype: object

In [55]:
# Python

import pandas as pd

# Example DataFrame with durations (timedelta)
data = {
    'task': ['Task A', 'Task B', 'Task C', 'Task D'],
    'duration': [pd.Timedelta(hours=5),
                 pd.Timedelta(hours=3, minutes=30),
                 pd.Timedelta(hours=4),
                 pd.Timedelta(hours=2, minutes=45)]
}

df = pd.DataFrame(data)

# Find the minimum duration
min_duration = df['duration'].min()

print(f"Minimum Duration: {min_duration}")

# Optionally, get the row(s) corresponding to the minimum duration
min_row = df[df['duration'] == min_duration]
print("", min_row)
# Row(s) with Minimum Duration:

Minimum Duration: 0 days 02:45:00
      task        duration
3  Task D 0 days 02:45:00

In [56]:
# Sample data: exercise log with Calories burned
data = {
    'Date': ['2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04'],
    'Activity': ['Running', 'Cycling', 'Swimming', 'Walking'],
    'Calories': [300, 250, 400, 150]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Calculate the average Calories burned
average_calories = df['Calories'].mean()

# Print the result
print(f"Average Calories burned: {average_calories:.2f}")

Average Calories burned: 275.00

In [57]:
# Python code
import pandas as pd

# Sample DataFrame with Date column as string
data = {
    'Date': ['2026-01-01', '2026-02-15', '2026-03-08'],
    'Value': [100, 200, 300]
}
df = pd.DataFrame(data)

# Convert 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d', errors='coerce')

# Verify the conversion
print(df)
print(df.dtypes)

        Date  Value
0 2026-01-01    100
1 2026-02-15    200
2 2026-03-08    300
Date     datetime64[ns]
Value             int64
dtype: object

In [58]:
print(df.isnull())

    Date  Value
0  False  False
1  False  False
2  False  False

In [62]:
df.fillna

<bound method NDFrame.fillna of         Date  Value
0 2026-01-01    100
1 2026-02-15    200
2 2026-03-08    300>

In [63]:
df = pd.DataFrame(data)

# Display original DataFrame
print("Original DataFrame:")
print(df)

# Calculate mean of Calories, skipping NaN values
mean_calories = df['Calories'].mean()

# Replace missing Calories values with the mean
df['Calories'] = df['Calories'].fillna(mean_calories)

# Display updated DataFrame
print("DataFrame After Replacing Missing Values:")
print(df)

df['Calories'].fillna(mean_calories, inplace=True)

Original DataFrame:
         Date  Value
0  2026-01-01    100
1  2026-02-15    200
2  2026-03-08    300

KeyError: 'Calories'

In [64]:
df.drop_duplicates(keep='first')

         Date  Value
0  2026-01-01    100
1  2026-02-15    200
2  2026-03-08    300

In [66]:
# Python
import pandas as pd

# Sample DataFrame with duplicate rows
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'David', 'Bob'],
    'Age': [25, 30, 25, 40, 30],
    'City': ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Karachi']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Step 1: Find duplicate rows
# This returns a boolean Series indicating duplicates (True for duplicate, False for first occurrence)
duplicates_mask = df.duplicated()
print("Duplicate mask (True means duplicate row):")
print(duplicates_mask)

# Step 2: Display only duplicates
duplicate_rows = df[df.duplicated()]
print("Duplicate rows:")
print(duplicate_rows)

# Step 3: Remove duplicate rows, keeping the first occurrence
df_no_duplicates = df.drop_duplicates()
print("DataFrame after removing duplicates (keeping first occurrence):")
print(df_no_duplicates)

# Optional: Remove duplicates while keeping the last occurrence
df_no_duplicates_last = df.drop_duplicates(keep='last')
print("DataFrame after removing duplicates (keeping last occurrence):")
print(df_no_duplicates_last)

# Optional: Remove duplicates based on specific columns only
df_no_duplicates_subset = df.drop_duplicates(subset=['Name', 'Age'])
print("DataFrame after removing duplicates based on 'Name' and 'Age':")
print(df_no_duplicates_subset)

Original DataFrame:
    Name  Age       City
0  Alice   25     Lahore
1    Bob   30    Karachi
2  Alice   25     Lahore
3  David   40  Islamabad
4    Bob   30    Karachi
Duplicate mask (True means duplicate row):
0    False
1    False
2     True
3    False
4     True
dtype: bool
Duplicate rows:
    Name  Age     City
2  Alice   25   Lahore
4    Bob   30  Karachi
DataFrame after removing duplicates (keeping first occurrence):
    Name  Age       City
0  Alice   25     Lahore
1    Bob   30    Karachi
3  David   40  Islamabad
DataFrame after removing duplicates (keeping last occurrence):
    Name  Age       City
2  Alice   25     Lahore
3  David   40  Islamabad
4    Bob   30    Karachi
DataFrame after removing duplicates based on 'Name' and 'Age':
    Name  Age       City
0  Alice   25     Lahore
1    Bob   30    Karachi
3  David   40  Islamabad

In [67]:
# Python
import pandas as pd

# Sample DataFrame
data = {
    'Task': ['Task A', 'Task B', 'Task C', 'Task D'],
    'Duration': [60, 120, 450, 30]  # 450 is likely incorrect
}
df = pd.DataFrame(data)

# Function to detect durations above a reasonable threshold (e.g., 240 minutes)
def detect_invalid_duration(duration, max_minutes=240):
    return duration > max_minutes

# Detect invalid durations
df['Invalid'] = df['Duration'].apply(detect_invalid_duration)

# Fix invalid durations: for demonstration, we'll set them to the median of valid values
median_valid_duration = df.loc[~df['Invalid'], 'Duration'].median()
df.loc[df['Invalid'], 'Duration'] = median_valid_duration

# Drop the helper column if desired
df.drop(columns='Invalid', inplace=True)

# Display the updated DataFrame
print(df)

     Task  Duration
0  Task A        60
1  Task B       120
2  Task C        60
3  Task D        30

In [69]:
# Python

import pandas as pd
import numpy as np

# Sample DataFrame
data = {
    'Date': ['2026-01-01', np.nan, '2026-03-05', None, '2026-03-08'],
    'Value': [10, 20, 30, 40, 50]
}

df = pd.DataFrame(data)

# Display original DataFrame
print("Original DataFrame:", df)

# Remove rows where the 'Date' column is missing
df_clean = df.dropna(subset=['Date'])

# Display cleaned DataFrame
print("DataFrame after removing missing dates:", df_clean)

Original DataFrame:          Date  Value
0  2026-01-01     10
1         NaN     20
2  2026-03-05     30
3        None     40
4  2026-03-08     50
DataFrame after removing missing dates:          Date  Value
0  2026-01-01     10
2  2026-03-05     30
4  2026-03-08     50

In [70]:
# Sample DataFrame with dates as strings or integers
data = {
    'date_str': ['20201226', '20210315', '20211201'],
    'value': [10, 20, 30]
}
df = pd.DataFrame(data)

# Convert 'date_str' to datetime format
df['date'] = pd.to_datetime(df['date_str'], format='%Y%m%d')

# Display the DataFrame
print(df)

   date_str  value       date
0  20201226     10 2020-12-26
1  20210315     20 2021-03-15
2  20211201     30 2021-12-01

In [71]:
# Sample DataFrame
data = {
    'Task': ['Task A', 'Task B', 'Task C', 'Task D'],
    'Duration': [45, 120, 30, 75]  # Duration in minutes
}

df = pd.DataFrame(data)

# Filter rows where Duration is greater than 60 minutes
df_filtered = df[df['Duration'] > 60]

# Display the filtered DataFrame
print(df_filtered)

     Task  Duration
1  Task B       120
3  Task D        75

In [73]:
# Sample DataFrame creation
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 37, 29],
    'Pulse': [102, 115, 110, 120]
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Filter rows where Pulse > 110 using boolean indexing
high_pulse_df = df[df['Pulse'] > 110]

# Display the filtered DataFrame
print("Filtered DataFrame (Pulse > 110):")
print(high_pulse_df)

Original DataFrame:
      Name  Age  Pulse
0    Alice   25    102
1      Bob   32    115
2  Charlie   37    110
3    David   29    120
Filtered DataFrame (Pulse > 110):
    Name  Age  Pulse
1    Bob   32    115
3  David   29    120

In [74]:
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Calories burned': [400, 320, 450, 300],
    'Workout': ['Running', 'Cycling', 'Swimming', 'Yoga']
}

df = pd.DataFrame(data)

# Filter rows where 'Calories burned' > 350
filtered_df = df[df['Calories burned'] > 350]

# Display the filtered DataFrame
print(filtered_df)

      Name  Calories burned   Workout
0    Alice              400   Running
2  Charlie              450  Swimming

In [75]:

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 28],
    'Pulse': [95, 102, 108, 115, 100]
}

df = pd.DataFrame(data)

# Filter rows where Pulse is between 100 and 110 (inclusive)
filtered_df = df[(df['Pulse'] >= 100) & (df['Pulse'] <= 110)]

# Display the filtered DataFrame
print(filtered_df)

      Name  Age  Pulse
1      Bob   30    102
2  Charlie   35    108
4      Eva   28    100

In [76]:
# Sample DataFrame
data = {
    'Date': ['2026-03-01', '2026-03-02', '2026-03-03'],
    'Duration': [30, 45, 60],
    'Calories': [200, 350, 400],
    'HeartRate': [80, 85, 90]
}

df = pd.DataFrame(data)

# Display only 'Duration' and 'Calories' columns
df_selected = df[['Duration', 'Calories']]

# Print the filtered DataFrame
print(df_selected)

   Duration  Calories
0        30       200
1        45       350
2        60       400

In [77]:
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Pulse': [72, 85, 90, 78]
}

df = pd.DataFrame(data)

# Calculate the average of the Pulse column
average_pulse = df['Pulse'].mean()

# Print the result
print(f"The average Pulse is: {average_pulse}")

The average Pulse is: 81.25

In [84]:
import pandas as pd
df1=pd.read_csv("C:\\Users\\osm\\Downloads\\generic-food.csv")

In [85]:
df1

,FOOD NAME,SCIENTIFIC NAME,GROUP,SUB GROUP
0,Angelica,Angelica keiskei,Herbs and Spices,Herbs
1,Savoy cabbage,Brassica oleracea var. sabauda,Vegetables,Cabbages
2,Silver linden,Tilia argentea,Herbs and Spices,Herbs
3,Kiwi,Actinidia chinensis,Fruits,Tropical fruits
4,Allium (Onion),Allium,Vegetables,Onion-family vegetables
...,...,...,...,...
901,White cabbage,Brassica oleracea L. var. capitata L. f. alba DC.,Vegetables,Cabbages
902,Romaine lettuce,Lactuca sativa L. var. longifolia,Vegetables,Leaf vegetables
903,dumplings,NaN,NaN,NaN
904,muesli,NaN,NaN,NaN
905,milk,NaN,NaN,NaN

In [90]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Pulse   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

      Name  Pulse
0    Alice     72
1      Bob     85
2  Charlie     90
3    David     78

In [92]:

# Sample data creation. Replace this with `pd.read_csv('your_file.csv')` if reading from a CSV file.
data = {
    'date': ['2025-12-01', '2025-12-05', '2025-11-20', '2025-12-15', '2025-12-31', '2025-10-10'],
    'calories_burned': [300, 450, 200, 500, 350, 150]
}

# Create DataFrame
df = pd.DataFrame(data)

# Ensure the 'date' column is datetime type
df['date'] = pd.to_datetime(df['date'])

# Filter data for December
december_data = df[df['date'].dt.month == 12]

# Calculate total calories burned in December
total_calories = december_data['calories_burned'].sum()

print(f"Total calories burned in December: {total_calories}")

Total calories burned in December: 1600

In [93]:
# Example dataset: You can load your dataset from a CSV file using pd.read_csv('filename.csv')
# Here we create a sample dataset
data = {
    'Workout': ['Running', 'Cycling', 'Swimming', 'Yoga', 'Weightlifting'],
    'Duration_minutes': [30, 45, 60, 50, 40]  # Duration of each workout in minutes
}

# Create a DataFrame
df = pd.DataFrame(data)

# Calculate the average duration of workouts
average_duration = df['Duration_minutes'].mean()

# Print the result
print(f"The average duration of workouts is {average_duration:.2f} minutes.")

The average duration of workouts is 45.00 minutes.

In [99]:


# Inspect the first few rows to ensure proper loading
print(df.head())
# Finding the maximum value in the 'Maxpulse' column
max_pulse = df['Maxpulse'].max()
print("Maximum Maxpulse value:", max_pulse)

# Optional: Find the row(s) corresponding to this maximum value
rows_with_max_pulse = df[df['Maxpulse'] == max_pulse]
print("Row(s) with the maximum Maxpulse value:", rows_with_max_pulse)

         Workout  Duration_minutes
0        Running                30
1        Cycling                45
2       Swimming                60
3           Yoga                50
4  Weightlifting                40

KeyError: 'Maxpulse'

In [100]:

# Sample dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Calories Burned': [300, 450, 200, 500]
}

# Create DataFrame
df = pd.DataFrame(data)

# Sort the DataFrame by 'Calories Burned' in descending order
df_sorted = df.sort_values(by='Calories Burned', ascending=False)

# Display the sorted DataFrame
print(df_sorted)

      Name  Calories Burned
3    David              500
1      Bob              450
0    Alice              300
2  Charlie              200

In [102]:
# Sample dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 22, 28],
    'Pulse': [80, 72, 90, 75]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the original dataset
print("Original Dataset:")
print(df)

# Sort the dataset by 'Pulse' in ascending order
df_sorted = df.sort_values(by='Pulse', ascending=True)

# Reset index if desired
df_sorted.reset_index(drop=True, inplace=True)

# Display the sorted dataset
print("Dataset Sorted by Pulse (Ascending):")
print(df_sorted)

Original Dataset:
      Name  Age  Pulse
0    Alice   25     80
1      Bob   30     72
2  Charlie   22     90
3    David   28     75
Dataset Sorted by Pulse (Ascending):
      Name  Age  Pulse
0      Bob   30     72
1    David   28     75
2    Alice   25     80
3  Charlie   22     90

In [103]:

# Sample dataset
data = {
    'Duration': [30, 45, 30, 60, 45, 60, 30],
    'Pulse': [80, 90, 85, 70, 88, 75, 82],
    'Calories': [200, 300, 250, 400, 350, 450, 220]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Group by 'Duration' and calculate average 'Pulse'
average_pulse = df.groupby('Duration')['Pulse'].mean().reset_index()

# Rename columns for clarity (optional)
average_pulse.rename(columns={'Pulse': 'Average_Pulse'}, inplace=True)

# Display the result
print(average_pulse)

   Duration  Average_Pulse
0        30      82.333333
1        45      89.000000
2        60      72.500000

In [104]:
# Sample workout data
workouts = [
    {"name": "Running", "calories_burned": 500},
    {"name": "Cycling", "calories_burned": 450},
    {"name": "Swimming", "calories_burned": 600},
    {"name": "Jump Rope", "calories_burned": 550},
    {"name": "HIIT", "calories_burned": 650},
    {"name": "Yoga", "calories_burned": 200},
    {"name": "Pilates", "calories_burned": 250},
    {"name": "Rowing", "calories_burned": 480}
]

# Sort workouts by calories_burned in descending order
sorted_workouts = sorted(workouts, key=lambda x: x["calories_burned"], reverse=True)

# Get top 5 workouts
top_5_workouts = sorted_workouts[:5]

# Display the results
print("Top 5 Workouts Based on Calories Burned:")
for i, workout in enumerate(top_5_workouts, start=1):
    print(f"{i}. {workout['name']} - {workout['calories_burned']} Calories")
    
# Example Output:
# Top 5 Workouts Based on Calories Burned:
# 1. HIIT - 650 Calories
# 2. Swimming - 600 Calories
# 3. Jump Rope - 550 Calories
# 4. Running - 500 Calories
# 5. Rowing - 480 Calories

Top 5 Workouts Based on Calories Burned:
1. HIIT - 650 Calories
2. Swimming - 600 Calories
3. Jump Rope - 550 Calories
4. Running - 500 Calories
5. Rowing - 480 Calories

In [ ]:
df.drop( )