In [141]:
# Demonstrate NumPy array creation methods and basic operations

import numpy as np

arr = np.array([2,4,6,8,10,12,14,16,18,20])
print(arr)

np.zeros([3,3])
# np.random.rand(2,45,33,67,95)

number = np.linspace(0,5,10)
print(number)

[ 2  4  6  8 10 12 14 16 18 20]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

In [142]:
arr.shape

(10,)

In [143]:
arr.dtype

dtype('int64')

In [144]:
arr.size

10

In [145]:
arr.ndim

1

In [146]:
arr.reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [147]:
x = arr.max()
y = arr.min()
print(x)
print(y)
arr[9]
arr[0]

20
2

np.int64(2)

In [148]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

arr2[0,1]

np.int64(2)

In [149]:
# Demonstrate broadcasting and universal functions.

import numpy as np

arr1 =np.array([[1,2,3],[4,5,6]])
arr2 =np.array([10,20,30])

arr3 = arr1 + arr2
print(arr3)
arr4 = arr1 - arr2
print(arr4)
arr5 = arr1 * arr2
print(arr5)
arr6 = arr1 % arr2
print(arr6)

[[11 22 33]
 [14 25 36]]
[[ -9 -18 -27]
 [ -6 -15 -24]]
[[ 10  40  90]
 [ 40 100 180]]
[[1 2 3]
 [4 5 6]]

In [150]:
arr10 = np.array([1,4,9,16,25])
print(np.sqrt(arr10))
print(np.exp(arr10))
print(np.sin(arr10))

[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

In [151]:
arr11 = np.array([[5,12,3],[8,2,7]])
print(arr11)
print(arr11.sum())
print(np.max(arr11 , axis=0))
print(np.min(arr11 , axis=0))

[[ 5 12  3]
 [ 8  2  7]]
37
[ 8 12  7]
[5 2 3]

In [152]:
print(arr1.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]]

In [1]:
# Perform basic exploratory data analysis using Pandas.

import pandas as pd

data = {
'Name': ['Alice','lena','Charlie','Diana','Eve','dina'],
'Age': [25,30,34,35,28,36],
'Score': [85,92,78,56,88,95],
'Grade': ['A','A','B','C','B','A']
}

df = pd.DataFrame(data)
df

      Name  Age  Score Grade
0    Alice   25     85     A
1     lena   30     92     A
2  Charlie   34     78     B
3    Diana   35     56     C
4      Eve   28     88     B
5     dina   36     95     A

In [2]:
df.head(3)

      Name  Age  Score Grade
0    Alice   25     85     A
1     lena   30     92     A
2  Charlie   34     78     B

In [3]:
df.shape

(6, 4)

In [4]:
df.columns

Index(['Name', 'Age', 'Score', 'Grade'], dtype='object')

In [5]:
df.dtypes

Name     object
Age       int64
Score     int64
Grade    object
dtype: object

In [6]:
df.isnull().sum()

Name     0
Age      0
Score    0
Grade    0
dtype: int64

In [7]:
mean_age = df['Age'].mean()
print("Mean age:", mean_age)

Mean age: 31.333333333333332

In [8]:
df["Age"] = df["Age"].fillna(mean_age)
df

      Name  Age  Score Grade
0    Alice   25     85     A
1     lena   30     92     A
2  Charlie   34     78     B
3    Diana   35     56     C
4      Eve   28     88     B
5     dina   36     95     A

In [9]:
df.dropna(inplace=True)
df

      Name  Age  Score Grade
0    Alice   25     85     A
1     lena   30     92     A
2  Charlie   34     78     B
3    Diana   35     56     C
4      Eve   28     88     B
5     dina   36     95     A

In [10]:
print(df[["Name", "Age"]])

      Name  Age
0    Alice   25
1     lena   30
2  Charlie   34
3    Diana   35
4      Eve   28
5     dina   36

In [11]:
high_scores = df[df['Score'] > 85]
print(high_scores)

   Name  Age  Score Grade
1  lena   30     92     A
4   Eve   28     88     B
5  dina   36     95     A

In [12]:
df.set_index('Name' , inplace=True)

In [13]:
df

         Age  Score Grade
Name
Alice     25     85     A
lena      30     92     A
Charlie   34     78     B
Diana     35     56     C
Eve       28     88     B
dina      36     95     A

In [14]:
unique_grades = df["Grade"].unique()
print(unique_grades)

['A' 'B' 'C']

In [15]:
grade_counts = df['Grade'].value_counts()
print(grade_counts)

Grade
A    3
B    2
C    1
Name: count, dtype: int64

In [16]:
sorted_df = df.sort_values('Score', ascending=False)
print(sorted_df)

         Age  Score Grade
Name
dina      36     95     A
lena      30     92     A
Eve       28     88     B
Alice     25     85     A
Charlie   34     78     B
Diana     35     56     C